package com.nchu.friends.po;

public class Homenote {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homenote.noteId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer noteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homenote.userName
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homenote.bgColor
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String bgcolor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homenote.likeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer likenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homenote.dislikeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer dislikenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homenote.note
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homenote.noteId
	 * @return  the value of homenote.noteId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getNoteid() {
		return noteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homenote.noteId
	 * @param noteid  the value for homenote.noteId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setNoteid(Integer noteid) {
		this.noteid = noteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homenote.userName
	 * @return  the value of homenote.userName
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homenote.userName
	 * @param username  the value for homenote.userName
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homenote.bgColor
	 * @return  the value of homenote.bgColor
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getBgcolor() {
		return bgcolor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homenote.bgColor
	 * @param bgcolor  the value for homenote.bgColor
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setBgcolor(String bgcolor) {
		this.bgcolor = bgcolor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homenote.likeNum
	 * @return  the value of homenote.likeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getLikenum() {
		return likenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homenote.likeNum
	 * @param likenum  the value for homenote.likeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setLikenum(Integer likenum) {
		this.likenum = likenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homenote.dislikeNum
	 * @return  the value of homenote.dislikeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getDislikenum() {
		return dislikenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homenote.dislikeNum
	 * @param dislikenum  the value for homenote.dislikeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setDislikenum(Integer dislikenum) {
		this.dislikenum = dislikenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homenote.note
	 * @return  the value of homenote.note
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homenote.note
	 * @param note  the value for homenote.note
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setNote(String note) {
		this.note = note;
	}
}