package com.nchu.friends.po;

import java.util.ArrayList;
import java.util.List;

public class HomenoteExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public HomenoteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andNoteidIsNull() {
			addCriterion("noteId is null");
			return (Criteria) this;
		}

		public Criteria andNoteidIsNotNull() {
			addCriterion("noteId is not null");
			return (Criteria) this;
		}

		public Criteria andNoteidEqualTo(Integer value) {
			addCriterion("noteId =", value, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidNotEqualTo(Integer value) {
			addCriterion("noteId <>", value, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidGreaterThan(Integer value) {
			addCriterion("noteId >", value, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidGreaterThanOrEqualTo(Integer value) {
			addCriterion("noteId >=", value, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidLessThan(Integer value) {
			addCriterion("noteId <", value, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidLessThanOrEqualTo(Integer value) {
			addCriterion("noteId <=", value, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidIn(List<Integer> values) {
			addCriterion("noteId in", values, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidNotIn(List<Integer> values) {
			addCriterion("noteId not in", values, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidBetween(Integer value1, Integer value2) {
			addCriterion("noteId between", value1, value2, "noteid");
			return (Criteria) this;
		}

		public Criteria andNoteidNotBetween(Integer value1, Integer value2) {
			addCriterion("noteId not between", value1, value2, "noteid");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("userName is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("userName is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("userName =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("userName <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("userName >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("userName >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("userName <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("userName <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("userName like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("userName not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("userName in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("userName not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("userName between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("userName not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andBgcolorIsNull() {
			addCriterion("bgColor is null");
			return (Criteria) this;
		}

		public Criteria andBgcolorIsNotNull() {
			addCriterion("bgColor is not null");
			return (Criteria) this;
		}

		public Criteria andBgcolorEqualTo(String value) {
			addCriterion("bgColor =", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorNotEqualTo(String value) {
			addCriterion("bgColor <>", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorGreaterThan(String value) {
			addCriterion("bgColor >", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorGreaterThanOrEqualTo(String value) {
			addCriterion("bgColor >=", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorLessThan(String value) {
			addCriterion("bgColor <", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorLessThanOrEqualTo(String value) {
			addCriterion("bgColor <=", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorLike(String value) {
			addCriterion("bgColor like", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorNotLike(String value) {
			addCriterion("bgColor not like", value, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorIn(List<String> values) {
			addCriterion("bgColor in", values, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorNotIn(List<String> values) {
			addCriterion("bgColor not in", values, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorBetween(String value1, String value2) {
			addCriterion("bgColor between", value1, value2, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andBgcolorNotBetween(String value1, String value2) {
			addCriterion("bgColor not between", value1, value2, "bgcolor");
			return (Criteria) this;
		}

		public Criteria andLikenumIsNull() {
			addCriterion("likeNum is null");
			return (Criteria) this;
		}

		public Criteria andLikenumIsNotNull() {
			addCriterion("likeNum is not null");
			return (Criteria) this;
		}

		public Criteria andLikenumEqualTo(Integer value) {
			addCriterion("likeNum =", value, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumNotEqualTo(Integer value) {
			addCriterion("likeNum <>", value, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumGreaterThan(Integer value) {
			addCriterion("likeNum >", value, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumGreaterThanOrEqualTo(Integer value) {
			addCriterion("likeNum >=", value, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumLessThan(Integer value) {
			addCriterion("likeNum <", value, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumLessThanOrEqualTo(Integer value) {
			addCriterion("likeNum <=", value, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumIn(List<Integer> values) {
			addCriterion("likeNum in", values, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumNotIn(List<Integer> values) {
			addCriterion("likeNum not in", values, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumBetween(Integer value1, Integer value2) {
			addCriterion("likeNum between", value1, value2, "likenum");
			return (Criteria) this;
		}

		public Criteria andLikenumNotBetween(Integer value1, Integer value2) {
			addCriterion("likeNum not between", value1, value2, "likenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumIsNull() {
			addCriterion("dislikeNum is null");
			return (Criteria) this;
		}

		public Criteria andDislikenumIsNotNull() {
			addCriterion("dislikeNum is not null");
			return (Criteria) this;
		}

		public Criteria andDislikenumEqualTo(Integer value) {
			addCriterion("dislikeNum =", value, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumNotEqualTo(Integer value) {
			addCriterion("dislikeNum <>", value, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumGreaterThan(Integer value) {
			addCriterion("dislikeNum >", value, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumGreaterThanOrEqualTo(Integer value) {
			addCriterion("dislikeNum >=", value, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumLessThan(Integer value) {
			addCriterion("dislikeNum <", value, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumLessThanOrEqualTo(Integer value) {
			addCriterion("dislikeNum <=", value, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumIn(List<Integer> values) {
			addCriterion("dislikeNum in", values, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumNotIn(List<Integer> values) {
			addCriterion("dislikeNum not in", values, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumBetween(Integer value1, Integer value2) {
			addCriterion("dislikeNum between", value1, value2, "dislikenum");
			return (Criteria) this;
		}

		public Criteria andDislikenumNotBetween(Integer value1, Integer value2) {
			addCriterion("dislikeNum not between", value1, value2, "dislikenum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table homenote
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table homenote
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 15 10:03:53 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}