package com.nchu.friends.po;

public class Msgreply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msgreply.replyId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer replyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msgreply.msgId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer msgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msgreply.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msgreply.isLike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Boolean islike;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msgreply.isDislike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Boolean isdislike;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msgreply.comment
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msgreply.replyId
	 * @return  the value of msgreply.replyId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getReplyid() {
		return replyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msgreply.replyId
	 * @param replyid  the value for msgreply.replyId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setReplyid(Integer replyid) {
		this.replyid = replyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msgreply.msgId
	 * @return  the value of msgreply.msgId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getMsgid() {
		return msgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msgreply.msgId
	 * @param msgid  the value for msgreply.msgId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setMsgid(Integer msgid) {
		this.msgid = msgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msgreply.userId
	 * @return  the value of msgreply.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msgreply.userId
	 * @param userid  the value for msgreply.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msgreply.isLike
	 * @return  the value of msgreply.isLike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Boolean getIslike() {
		return islike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msgreply.isLike
	 * @param islike  the value for msgreply.isLike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setIslike(Boolean islike) {
		this.islike = islike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msgreply.isDislike
	 * @return  the value of msgreply.isDislike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Boolean getIsdislike() {
		return isdislike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msgreply.isDislike
	 * @param isdislike  the value for msgreply.isDislike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setIsdislike(Boolean isdislike) {
		this.isdislike = isdislike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msgreply.comment
	 * @return  the value of msgreply.comment
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msgreply.comment
	 * @param comment  the value for msgreply.comment
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}