package com.nchu.friends.po;

public class Notereply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notereply.replyId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer replyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notereply.noteId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer noteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notereply.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notereply.isLike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Boolean islike;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notereply.isDislike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Boolean isdislike;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notereply.replyId
	 * @return  the value of notereply.replyId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getReplyid() {
		return replyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notereply.replyId
	 * @param replyid  the value for notereply.replyId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setReplyid(Integer replyid) {
		this.replyid = replyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notereply.noteId
	 * @return  the value of notereply.noteId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getNoteid() {
		return noteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notereply.noteId
	 * @param noteid  the value for notereply.noteId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setNoteid(Integer noteid) {
		this.noteid = noteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notereply.userId
	 * @return  the value of notereply.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notereply.userId
	 * @param userid  the value for notereply.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notereply.isLike
	 * @return  the value of notereply.isLike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Boolean getIslike() {
		return islike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notereply.isLike
	 * @param islike  the value for notereply.isLike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setIslike(Boolean islike) {
		this.islike = islike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notereply.isDislike
	 * @return  the value of notereply.isDislike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Boolean getIsdislike() {
		return isdislike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notereply.isDislike
	 * @param isdislike  the value for notereply.isDislike
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setIsdislike(Boolean isdislike) {
		this.isdislike = isdislike;
	}
}