package com.nchu.friends.po;

import java.util.Date;

public class Usermsg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.msgId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer msgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.msgTitle
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String msgtitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.msgDate
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Date msgdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.commentNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer commentnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.likeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer likenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.dislikeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer dislikenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usermsg.msgBody
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String msgbody;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.msgId
	 * @return  the value of usermsg.msgId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getMsgid() {
		return msgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.msgId
	 * @param msgid  the value for usermsg.msgId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setMsgid(Integer msgid) {
		this.msgid = msgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.userId
	 * @return  the value of usermsg.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.userId
	 * @param userid  the value for usermsg.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.msgTitle
	 * @return  the value of usermsg.msgTitle
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getMsgtitle() {
		return msgtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.msgTitle
	 * @param msgtitle  the value for usermsg.msgTitle
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setMsgtitle(String msgtitle) {
		this.msgtitle = msgtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.msgDate
	 * @return  the value of usermsg.msgDate
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Date getMsgdate() {
		return msgdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.msgDate
	 * @param msgdate  the value for usermsg.msgDate
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setMsgdate(Date msgdate) {
		this.msgdate = msgdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.commentNum
	 * @return  the value of usermsg.commentNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getCommentnum() {
		return commentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.commentNum
	 * @param commentnum  the value for usermsg.commentNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setCommentnum(Integer commentnum) {
		this.commentnum = commentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.likeNum
	 * @return  the value of usermsg.likeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getLikenum() {
		return likenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.likeNum
	 * @param likenum  the value for usermsg.likeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setLikenum(Integer likenum) {
		this.likenum = likenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.dislikeNum
	 * @return  the value of usermsg.dislikeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getDislikenum() {
		return dislikenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.dislikeNum
	 * @param dislikenum  the value for usermsg.dislikeNum
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setDislikenum(Integer dislikenum) {
		this.dislikenum = dislikenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usermsg.msgBody
	 * @return  the value of usermsg.msgBody
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getMsgbody() {
		return msgbody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usermsg.msgBody
	 * @param msgbody  the value for usermsg.msgBody
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setMsgbody(String msgbody) {
		this.msgbody = msgbody;
	}
}