package com.nchu.friends.po;

public class Userinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userinfo.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userinfo.userName
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userinfo.userPsw
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String userpsw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userinfo.userSex
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String usersex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userinfo.userQQ
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private String userqq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userinfo.loginFlag
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	private Integer loginflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userinfo.userId
	 * @return  the value of userinfo.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userinfo.userId
	 * @param userid  the value for userinfo.userId
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userinfo.userName
	 * @return  the value of userinfo.userName
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userinfo.userName
	 * @param username  the value for userinfo.userName
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userinfo.userPsw
	 * @return  the value of userinfo.userPsw
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getUserpsw() {
		return userpsw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userinfo.userPsw
	 * @param userpsw  the value for userinfo.userPsw
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUserpsw(String userpsw) {
		this.userpsw = userpsw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userinfo.userSex
	 * @return  the value of userinfo.userSex
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getUsersex() {
		return usersex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userinfo.userSex
	 * @param usersex  the value for userinfo.userSex
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUsersex(String usersex) {
		this.usersex = usersex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userinfo.userQQ
	 * @return  the value of userinfo.userQQ
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public String getUserqq() {
		return userqq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userinfo.userQQ
	 * @param userqq  the value for userinfo.userQQ
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setUserqq(String userqq) {
		this.userqq = userqq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userinfo.loginFlag
	 * @return  the value of userinfo.loginFlag
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public Integer getLoginflag() {
		return loginflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userinfo.loginFlag
	 * @param loginflag  the value for userinfo.loginFlag
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	public void setLoginflag(Integer loginflag) {
		this.loginflag = loginflag;
	}
}