package com.nchu.friends.mapper;

import com.nchu.friends.po.Usermsg;
import com.nchu.friends.po.UsermsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsermsgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	long countByExample(UsermsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int deleteByExample(UsermsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer msgid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int insert(Usermsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int insertSelective(Usermsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	List<Usermsg> selectByExampleWithBLOBs(UsermsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	List<Usermsg> selectByExample(UsermsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	Usermsg selectByPrimaryKey(Integer msgid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Usermsg record, @Param("example") UsermsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") Usermsg record, @Param("example") UsermsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByExample(@Param("record") Usermsg record, @Param("example") UsermsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByPrimaryKeySelective(Usermsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Usermsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usermsg
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByPrimaryKey(Usermsg record);
}