package com.nchu.friends.mapper;

import com.nchu.friends.po.Userinfo;
import com.nchu.friends.po.UserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	long countByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int deleteByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int insert(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int insertSelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	List<Userinfo> selectByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	Userinfo selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByExample(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByPrimaryKeySelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userinfo
	 * @mbg.generated  Sat Apr 22 01:20:07 CST 2017
	 */
	int updateByPrimaryKey(Userinfo record);
}